### ISSUE TITLE
Collection RXL file missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#606]
Document: https://github.com/metanorma/itu-X.arch-design

In `site generate`, a collection is generated but it is not included in the site because the `collection.rxl` file is missing.

This task is to produce that for every collection.

**Comment by opoudjis** [comment]
rxl is force-output in compiling individual documents when running under site generate:

````
      def get_extensions(options)
        ext = extract_extensions(options)
        !ext.include?(:presentation) && ext.any? do |e|
          @processor.use_presentation_xml(e)
        end and ext << :presentation
        !ext.include?(:rxl) && options[:site_generate] and
          ext << :rxl
        ext
      end
````

... Does `options[:site_generate]` propagate to the call to generate collections? I have no idea, so I might as well just always generate it with collections.

**Comment by opoudjis** [comment]
I am generating collection.rxl now, but the site index still only includes the two documents:

<img width="1275" alt="Image" src="https://github.com/user-attachments/assets/4ab43502-ee8b-45a6-9f65-e889192e812f" />

<img width="344" alt="Image" src="https://github.com/user-attachments/assets/65da6ddc-1cb7-4354-bb31-5e617d0a7e0a" />

@ribose-jeffreylau Can I pass this to you to investigate?

**Comment by ronaldtse** [comment]
@ribose-jeffreylau can you help address this? Thanks.

**Comment by ribose-jeffreylau** [comment]
I could only see the exact same two files listed in the [sources/collection.yml](https://github.com/metanorma/itu-X.arch-design/blob/1bd347237308d7291f039d68fca73543efb4d341/sources/collection.yml):

```yaml
# ...
manifest:
  level: document
  title: Document

  docref:

  - file: contribution/document.adoc
    identifier: SG17-C3000

  - file: recommendation/document.adoc
    identifier: ITU-X.arch-design
```

... as those listed in [metanorma.yml](https://github.com/metanorma/itu-X.arch-design/blob/1bd347237308d7291f039d68fca73543efb4d341/metanorma.yml):

```yaml
---
metanorma:
  source:
    files:

      # Recommendation
      - sources/recommendation/document.adoc

      # Contribution
      - sources/contribution/document.adoc

      # Contribution bundle
      - sources/collection.yml

# ...
```

So is it working as intended?
